# Big Node - Delegation Server Only
# This node provides GPU computation services for small nodes
# It does NOT participate in blockchain consensus
# All services are defined in docker-compose.mlnode.yml

version: '3.8'
services: {}
